# ---- Global: Variables ----
icons_format = "{icon} "

# ---- Global: Theme ----
[theme]
theme = "slick"

# ---- Global: Icons ----
[icons]
icons = "awesome6"

# ---- Block: Disk Space ----
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /home: $available.eng(w:2) "

# ---- Block: CPU ----
[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "memory"
format = " $icon $mem_total_used "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
interval = 1

# ---- Block: GPU ----
[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon  $temperature $utilization"

# ---- Block: Sound ----
#[[block]]
#block = "sound"
#format = " $icon $output_name{ $volume|} "
#[block.mappings]
#"alsa_output.pci-0000_00_1f.3.analog-stereo" = "Headset"

# ---- Block: Net ----
[[block]]
block = "net"
format = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

# ---- Block: Time ----
[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:' %a %d/%m %T') MST "

