theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home(avail) ::"
info_type = "available"
unit = "GB"
interval = 300

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUp}%"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
icons = true
clickable = true
warning_mem = 65
warning_swap = 50
critical_mem = 90
critical_swap = 75
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 1
format = "%a %B %d, %G %r MST"
