#!/usr/bin/env bash

# --- Initialize Submodules ---
cd ${HOME}
echo "Updating/Initializing submodules"
yadm submodule update --recursive --init

# --- Install & configure zpresto ---
source ${HOME}/.yadm/neededfunctions.sh
install_zsh_inf
install_prezto_yadm

# --- Bootstrapping Vim ---
if command -v vim >/dev/null 2>&1; then
	echo "Bootstrapping Vim"
	if [ -d "${HOME}/.vim/bundle/Vundle.vim" ]; then
		echo "Vundle is already installed, continuing with plugins"
		vim '+PluginInstall' '+PluginUpdate' '+PluginClean' '+qall'
	elif [ ! -d "${HOME}/.vim/bundle/Vundle.vim" ]; then
		echo "Vundle not found. Installing"
		git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
		vim '+PluginInstall' '+PluginClean' '+qall'
	fi
fi
